In [134]:
import numpy as np
import random as rng
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection



In [135]:
class Rubix_face():

    # face is a 3x3 matrix
    # name is the name of the face
    #left, right, up, down are the index of the faces that are adjacent to the face
    def __init__(self, name, index ,left, right, up, down):
        self.face = np.zeros((3,3))
        self.face = self.face + index
        self.name = name
        self.left = left
        self.right = right
        self.up = up
        self.down = down


class Rubix_cube():

    def __init__(self):
        #intializse a cube of 6 faces, 3x3 the front face is white
        self.cube = [None] * 6
        self.cube[0] = Rubix_face(name = 'White', index = 0,  up = 1, down = 3, left = 4, right = 5) # White
        self.cube[1] = Rubix_face(name = 'Red', index = 1, up = 2, down = 0, left = 4, right = 5) # red
        self.cube[2] = Rubix_face(name = 'Yellow', index = 2, up = 3, down = 1, left = 4, right = 5) # Yellow
        self.cube[3] = Rubix_face(name = 'Orange', index = 3, up = 0, down = 2, left = 4, right = 5) # Orange
        self.cube[4] = Rubix_face(name = 'Blue', index = 4, up = 1, down = 3, left = 2, right = 0) # Blue
        self.cube[5] = Rubix_face(name = 'Green', index = 5, up = 1, down = 3, left = 0, right = 2) # Green
    
    def print_cube(self):
        for i in range(6):
            print(self.cube[i].name)
            print(self.cube[i].face)
            print('\n')
        
    
    #def moves
    # rotate R moves the right face clockwise
    # rotate R' moves the right face counter clockwise
    # rotate L moves the left face clockwise
    # rotate L' moves the left face counter clockwise
    # rotate U moves the upper face clockwise
    # rotate U' moves the upper face counter clockwise
    # rotate D moves the down face clockwise
    # rotate D' moves the down face counter clockwise
    # rotate F moves the front face clockwise
    # rotate F' moves the front face counter clockwise
    # rotate B moves the back face clockwise
    # rotate B' moves the back face counter clockwise
    # each move has a direction, the prime is the normal opperation in the opposite direction
    def rotate_face(self,face = 0, direction = 0):
        #get the adjacent faces
        right = self.cube[face].right
        left = self.cube[face].left
        up = self.cube[face].up
        down = self.cube[face].down

        # rotate face clockwise
        if direction == 0:
            # rotate the face   
            self.cube[face].face = np.rot90(self.cube[face].face, 1)

            # rotate the adjacent faces
            #make a copy of the bottom face
            downcpy = self.cube[down].face.copy()

            #update down face
            self.cube[down].face[0,:] = self.cube[right].face[:,0]

            #update right face
            self.cube[right].face[:,0] = self.cube[up].face[2,:]

            #update up face
            self.cube[up].face[2,:] = self.cube[left].face[:,2]

            #update left face
            self.cube[left].face[:,2] = downcpy[0,:]



            

        









In [136]:
# make a cube
cube = Rubix_cube()
# print the fadjacent faces of cube[0]
face = cube.cube[0]
print(f"name:" + face.name)
print(face.face)
print(f"left: {cube.cube[face.left].name}")
print(cube.cube[face.left].face)
print(f"right: {cube.cube[face.right].name}")
print(cube.cube[face.right].face)
print(f"up: {cube.cube[face.up].name}")
print(cube.cube[face.up].face)
print(f"down: {cube.cube[face.down].name}")
print(cube.cube[face.down].face)


name:White
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
left: Blue
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
right: Green
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
up: Red
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
down: Orange
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [139]:
#print the adjacent faces of cube[1]
face = cube.cube[1]
print(f"name:" + face.name)
print(face.face)
print(f"left: {cube.cube[face.left].name}")
print(cube.cube[face.left].face)
print(f"right: {cube.cube[face.right].name}")
print(cube.cube[face.right].face)
print(f"up: {cube.cube[face.up].name}")
print(cube.cube[face.up].face)
print(f"down: {cube.cube[face.down].name}")
print(cube.cube[face.down].face)


name:Red
[[1. 1. 1.]
 [1. 1. 1.]
 [4. 4. 4.]]
left: Blue
[[4. 4. 3.]
 [4. 4. 3.]
 [4. 4. 3.]]
right: Green
[[1. 5. 5.]
 [1. 5. 5.]
 [1. 5. 5.]]
up: Yellow
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
down: White
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [138]:
# rotate the face clockwise
cube.rotate_face(face = 0, direction = 0)
cube.print_cube()


White
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Red
[[1. 1. 1.]
 [1. 1. 1.]
 [4. 4. 4.]]


Yellow
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


Orange
[[5. 5. 5.]
 [3. 3. 3.]
 [3. 3. 3.]]


Blue
[[4. 4. 3.]
 [4. 4. 3.]
 [4. 4. 3.]]


Green
[[1. 5. 5.]
 [1. 5. 5.]
 [1. 5. 5.]]


